# Generated by Django 5.0.7 on 2024-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='short_url',
            field=models.CharField(max_length=100),
        ),
    ]
