# Generated by Django 5.0.7 on 2024-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_alter_urldb_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='url',
            field=models.URLField(),
        ),
    ]
